default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jw_todo_development

test:
  <<: *default
  database: jw_todo_test

production:
  <<: *default
  database: jw_todo_production
  username: jw_todo
  password: <%= ENV["JW_TODO_DATABASE_PASSWORD"] %>

cable:
  <<: *default
  database: jw_todo_production
  username: jw_todo
  password: <%= ENV["JW_TODO_DATABASE_PASSWORD"] %>
